### ISSUE TITLE
create a function "markAsComplete"

### ISSUE THREAD

**Issue by rebecacalvoquintero** [FAC-11/week2-atoms#3]
create a function that will mark my tasks as complete in my todoapp

- The todos argument-array should be unchanged globally
- IdtoMark should be added;
-All other elements should be unchanged, except one with IdToMark
-Toggle Value

**Comment by mineshmshah** [comment]
Completed. We showed initially with checks but now have a css tick function to be clearer. Also divided into sections using this.
