### ISSUE TITLE
Buttons have no focus styles

### ISSUE THREAD

**Issue by oliverjam** [FAC-11/week2-atoms#52]
You have `outline: none` set for all your buttons. If you're going to remove the browser defaults it's really important to replace them with something so that keyboard-only users can see what they're interacting with.

**Comment by polyccon** [comment]
Thank you it should work now,

**Comment by oliverjam** [comment]
Thanks @polyccon. It would be good to reference this issue in the pull request so that it's easy for me to see exactly where you fixed this. You can put "Relates #52" in the body of the PR, which will link the two together
