### ISSUE TITLE
perhaps change title of your tests? 

### ISSUE THREAD

**Issue by y-zaky** [FAC-11/week2-atoms#55]
Instead of having to repeat yourselves when naming all of your tests, it might be easier to take a different approach. For example, for your first test, instead of repeating the phrase: 'should return an array'  on the following lines:

https://github.com/FAC-11/week2-atoms/blob/master/test.js#L5   (first line)
https://github.com/FAC-11/week2-atoms/blob/master/test.js#L8 (second line)

It might be more clear to always keep the first line to be the name of the function this test refers to . i.e. "deleteTodo function'.

 Then have the second line to be the actual feature this test will test, so keep it as "should return an array".

**Comment by oliverjam** [comment]
It might be worth having another look at the template I laid out in the intro to testing workshop:

```js
// Answer these questions for each unit test you write:
test('What component aspect are you testing?', function(assert) {
  const actual = 'What is the actual output?';
  const expected = 'What is the expected output?';

  assert.equal(actual, expected, 'What should the feature do?');
  assert.end();
});
```

The first string you give to the test describes what feature you're testing. The second string (given to the assertions) is to describe what the feature you're testing _should_ do.
